{{- include "ffc-helm-library.container-secret" (list . "coreai-mcu-persona.container-secret") -}}
{{- define "coreai-mcu-persona.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
