services:
  coreai-mcu-personas:
    build:
      context: .
      target: production
    image: coreai-mcu-personas
    container_name: coreai-mcu-personas
    depends_on:
      - coreai-mcu-personas-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-personas-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  coreai-mcu-personas-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: coreai-mcu-personas
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
