version: '3.8'
# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  coreai-mcu-personas:
    build:
      target: development
    image: coreai-mcu-personas-development
    container_name: coreai-mcu-personas-development
    ports:
      - "${CORE_AI_PERSONA_PORT:-3000}:3000"
      - "${CORE_AI_PERSONA_DEBUG_PORT:-9229}:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
  environment:
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}

  coreai-mcu-persona-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: coreai-mcu-persona-azurite
    ports:
      - "${CORE_AI_PROMPTS_TABLE_PORT:-10002}:10002"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
