services:
  coreai-mcu-personas:
    build:
      context: .
      target: production
    image: coreai-mcu-personas
    container_name: coreai-mcu-personas
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-personas-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}

  coreai-mcu-persona-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: coreai-mcu-persona-azurite
